AllCops:
  Exclude:
    - "vendor/**/*"
  TargetRubyVersion: 2.7

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - "test/**/*"
  Max: 150

Metrics/LineLength:
  Max: 100
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Max: 20
