AllCops:
  Exclude:
  - 'vendor/**/*'
  TargetRubyVersion: 2.1

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Exclude:
  - 'test/**/*'

Metrics/LineLength:
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https

Metrics/MethodLength:
  Max: 20
